apiVersion: v1
name: hello-world-humble
metadata:
  namespace: ros-default
  appVersion: dev-1
  targetRobot: dummy-1
rosmodules:
  - name: hello-world-talker
    repo: hub.kuberos.io
    image: fogrobo.com:5050/kuberos/kuberos_examples/ros_basic_tutorials/hello_world:v0
    type: pod
    target: dummy-1
    launch: ["ros2 run examples_rclpy_minimal_publisher publisher_local_function"]
  - name: hello-world-listener
    repo: hub.kuberos.io
    image: fogrobo.com:5050/kuberos/kuberos_examples/ros_basic_tutorials/hello_world:v0
    type: pod
    target: dummy-2
    launch: ["ros2 run examples_rclpy_minimal_subscriber subscriber_lambda"]
